### ISSUE TITLE
Almost works!! Arch Linux + Lutris

### ISSUE THREAD

**Issue by ZeroKun265** [daglaroglou/league-rpc-linux#1]
I ran it, it checked that discord and league were running and gave no other output.
![Screenshot_20230608_172530](https://github.com/daglaroglou/league-rpc-linux/assets/64660715/8b1aac41-cc11-46ab-9090-14422a5f3411)
This is what it showed in the preview, which gave me hope but then..
![image](https://github.com/daglaroglou/league-rpc-linux/assets/64660715/1bac8e6c-edd9-416c-8dbf-d0d7b2f99e5b)
Yeah, it doesn't actually fully work, any idea why?

**Comment by ZeroKun265** [comment]
Wait, nvm it works now.. that's weird, i was about to try and modify it my self, i restarted and it worked.
I'll do more tests and i'll close the issue if necessary

**Comment by ZeroKun265** [comment]
Ok nvm it probably got glitched with another method i was testing for rpc and now it's fine

**Comment by daglaroglou** [comment]
i use Manjaro (Arch based distro) and works fine for me... the code is a little mess but yeah. Im glad you gave feedback, let alone that it works, thanks :D
