### ISSUE TITLE
Can I include this on a Launcher? (question)

### ISSUE THREAD

**Issue by monadoenchant** [daglaroglou/league-rpc-linux#3]
Hey! So, I use [this league launcher](https://github.com/kassindornelles/lol-for-linux-installer/) to play and configure the game on Linux. I eventually came into this script, and I thought it was great, so I quickly made a addition to my own local copy of the launcher to add Rich Presence support, and it's working wonders. So [I made a PR ](https://github.com/kassindornelles/lol-for-linux-installer/pull/65)to add support for **Discord Rich Presence** from the launcher, installing and launching this script alongside the game. The question I wanted to make is, is it alright for me to include this in? I wanted to get your approval, so if it isn't cool with you I can just take the fork down.
Cheers and great work!

**Comment by daglaroglou** [comment]
Sure, no problem. I will try to keep this updated as well but i cant make my linux partition work so... idk when ill maintain it

**Comment by monadoenchant** [comment]
Thanks a lot! I'll try to contribute in here aswell, maybe add TFT support or Arena and stuff.

**Comment by daglaroglou** [comment]
Yeah, TFT is next :)

**Comment by monadoenchant** [comment]
Sorry for necro-ing this issue for it, but is there a reason why a fanmade icon is used, instead of the official one found [here](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/LoL_icon.svg/2048px-LoL_icon.svg.png), for example?

**Comment by daglaroglou** [comment]
well i wanted to give different touch to it that would look more linux-like... you can change it if you want
